import express from 'express';
import cars from './cars';
import profiles from './profiles';
import types from './types';
import makes from './makes';
import meta from './meta';
import booking from './booking';
import users from './users';
import banks from './banks';
import addresses from './addresses';
import inquiries from './inquiries';
import insurance from './insurance';
import notifications from './notifications';
import payouts from './payouts';
import payments from './payments';
import gallery from './gallery';
import generalInquiries from './generalInquiries';
import stations from './stations';
import rides from './rides';
import wallet from './wallet';
import transactions from './transactions';
import UserRides from './userRides';
import dropoffStations from './dropoffStations';
import pickupStations from './pickupStations';
import activities from './activities';
import suppliers from './suppliers';

const router = express.Router();

router.use('/cars', cars);
router.use('/profiles', profiles);
router.use('/types', types);
router.use('/makes', makes);
router.use('/meta', meta);
router.use('/booking', booking);
router.use('/users', users);
router.use('/banks', banks);
router.use('/payouts', payouts);
router.use('/payments', payments);
router.use('/address', addresses);
router.use('/inquiries', inquiries);
router.use('/insurance', insurance);
router.use('/notifications', notifications);
router.use('/gallery', gallery);
router.use('/general-inquiries', generalInquiries);
router.use('/stations', stations);
router.use('/rides', rides);
router.use('/wallet', wallet);
router.use('/transactions', transactions);
router.use('/user-rides', UserRides);
router.use('/ride-stations/dropoff', dropoffStations);
router.use('/ride-stations/pickup', pickupStations);
router.use('/activities', activities);
router.use('/suppliers', suppliers);

export default router;
