// Import all Mongoose model definitions to register them with mongoose
import './models/User'
import './models/Role'
import './models/Company'
import './models/Customer'
import './models/CarType'
import './models/CarMake'
import './models/CarModel'
import './models/Supplier'
import './models/Booking'
import './models/BookingDetail'
import './models/Invoice'
import './models/Schedule'
import './models/PriceList'
import './models/Notification'
import './models/Inquiry'
import './models/ResetPassword'
import './models/VerifyEmail'
import './models/Car'
import './models/DiscountTier'

export {}
