import { v4 as uuidv4 } from 'uuid';
const types = [
  {
    id: uuidv4(),
    name: 'Access Bank',
    logo: null,
    IBAN: null,
    address: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Bank of Africa',
    logo: null,
    IBAN: null,
    address: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Bank of Kigali',
    logo: null,
    IBAN: null,
    address: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Banque Populaire du Rwanda',
    logo: null,
    IBAN: null,
    address: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Cogebanque',
    logo: null,
    IBAN: null,
    address: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Equity Bank',
    logo: null,
    IBAN: null,
    address: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'Guaranty Trust Bank',
    logo: null,
    IBAN: null,
    address: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'I&M Bank',
    logo: null,
    IBAN: null,
    address: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'KCB Bank',
    logo: null,
    IBAN: null,
    address: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: uuidv4(),
    name: 'NCBA Bank',
    logo: null,
    IBAN: null,
    address: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default {
  up: (queryInterface) => queryInterface.bulkInsert('Banks', types, {}),

  down: (queryInterface) => queryInterface.bulkDelete('Banks', null, {}),
};
